In [4]:
import itertools
import numpy as np
import time

# Пораждающие наборы для решетки Личи

## Определение 12

In [30]:
GolayWords = [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]
shag = 0
for nabor in itertools.product([0, 1], repeat=24):
    shag += 1
    if shag % 100000 == 0:
        print(shag, len(GolayWords))
    nabor = list(nabor)
    item = 0
    diff_bolshe = True
    while item < len(GolayWords) and diff_bolshe:
        diff = 0
        for i in range(24):
            if GolayWords[item][i] != nabor[i]:
                diff += 1
        if diff < 8:
            diff_bolshe = False
        item += 1
    if diff_bolshe:
        GolayWords.append(nabor)

100000 32
200000 36
300000 64
400000 100
500000 128
600000 132
700000 182
800000 198
900000 224
1000000 232
1100000 256
1200000 300
1300000 320
1400000 352
1500000 352
1600000 396
1700000 416
1800000 430
1900000 448
2000000 496
2100000 512
2200000 532
2300000 576
2400000 596
2500000 608
2600000 628
2700000 672
2800000 672
2900000 704
3000000 728
3100000 768
3200000 796
3300000 800
3400000 828
3500000 846
3600000 892
3700000 896
3800000 928
3900000 960
4000000 992
4100000 992
4200000 1024
4300000 1044
4400000 1088
4500000 1108
4600000 1120
4700000 1141
4800000 1184
4900000 1184
5000000 1216
5100000 1240
5200000 1280
5300000 1308
5400000 1312
5500000 1340
5600000 1360
5700000 1406
5800000 1408
5900000 1442
6000000 1472
6100000 1504
6200000 1504
6300000 1540
6400000 1568
6500000 1572
6600000 1600
6700000 1638
6800000 1664
6900000 1672
7000000 1723
7100000 1738
7200000 1760
7300000 1774
7400000 1792
7500000 1836
7600000 1856
7700000 1888
7800000 1888
7900000 1940
8000000 1952
8100000 1972


In [37]:
nabor_12 = []
for i in range(24):
    for word in GolayWords:
        vector = [-1]*24
        vector[i] = 3
        for j in range(24):
            if word[j] == 1 and vector[j] == 3:
                vector[i] = -3
            elif word[j] == 1 and vector[j] == -1:
                vector[i] = 1
        nabor_12.append(vector)
np.array(nabor_12)

array([[ 3, -1, -1, ..., -1, -1, -1],
       [ 1, -1, -1, ..., -1, -1, -1],
       [ 1, -1, -1, ..., -1, -1, -1],
       ...,
       [-1, -1, -1, ..., -1, -1,  1],
       [-1, -1, -1, ..., -1, -1,  1],
       [-1, -1, -1, ..., -1, -1,  1]])

## Определение 13

In [18]:
nabor_13 = [] # список пораждающих векторов

#выведем набор квадратичных вычетов по модулю 23
nums = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]

#Критерий Эйлера.  Если число а в степени (p-1)/2 сравнимо с 1 по модулю p, то оно вычет
vichets = [0]
for num in nums:
    if (num**((23-1)/2) - 1) % 23 == 0:
        vichets.append(num)

#1
for i in range(23):
    vector = [0]*24
    vichets_sdvig = []
    for vichet in vichets:
        vichets_sdvig.append((vichet + i) % 24)
    for coordinata in vichets_sdvig:
        vector[coordinata] = 2
    nabor_13.append(vector)

#2
nabor_13.append([-3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

#3
for i in range(24):
    for j in range(24):
        if i < j:
            for znaki in [[1, 1], [-1, -1], [1, -1], [-1, 1]]:
                vector = [0]*24
                vector[i] = 4 * znaki[0]
                vector[j] = 4 * znaki[1]
                nabor_13.append(vector)
    


np.array(nabor_13)

array([[ 2,  2,  2, ...,  0,  0,  0],
       [ 0,  2,  2, ...,  0,  0,  0],
       [ 0,  0,  2, ...,  0,  0,  0],
       ...,
       [ 0,  0,  0, ...,  0, -4, -4],
       [ 0,  0,  0, ...,  0,  4, -4],
       [ 0,  0,  0, ...,  0, -4,  4]])

In [23]:
len(nabor_13) == 23*24*2 + 23 + 1

True

## Определение 14

In [25]:
nabor_14 = [
[8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[4, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[4, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[4, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[4, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[4, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[4, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[4, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[4, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[2, 2, 2, 2, 0, 0, 0, 0, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[2, 2, 0, 0, 2, 2, 0, 0, 2, 2, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[2, 0, 0, 2, 2, 0, 0, 2, 2, 0, 0, 2, 2, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0],
[4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0],
[2, 0, 2, 0, 2, 0, 0, 2, 2, 2, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0],
[2, 0, 0, 2, 2, 2, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0],
[2, 2, 0, 0, 2, 0, 2, 0, 2, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0],
[0, 2, 2, 2, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 2, 2, 0, 0, 2, 2, 0, 0, 2, 2, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
[-3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
]
np.array(nabor_14)

array([[ 8,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0],
       [ 4,  4,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0],
       [ 4,  0,  4,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0],
       [ 4,  0,  0,  4,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0],
       [ 4,  0,  0,  0,  4,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0],
       [ 4,  0,  0,  0,  0,  4,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0],
       [ 4,  0,  0,  0,  0,  0,  4,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0],
       [ 4,  0,  0,  0,  0,  0,  0,  0,  4,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0, 